# Generated by Django 5.0.4 on 2024-08-29 05:49

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Área Temática',
                'verbose_name_plural': 'Áreas Temáticas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('edicao', models.CharField(max_length=50, verbose_name='Edição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_encerramento', models.DateField(verbose_name='Data de Encerramento')),
                ('texto_apresentacao', models.TextField(verbose_name='Texto de Apresentação')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.fields.FormatStringFileUpload('eventos/logo/{instance.id}/{filename}'), verbose_name='Logo')),
                ('imagem_promocional', models.ImageField(blank=True, null=True, upload_to=core.fields.FormatStringFileUpload('eventos/imagem/{instance.id}/{filename}'), verbose_name='Imagem Promocional')),
                ('video_promocional', models.URLField(blank=True, null=True, verbose_name='Vídeo Promocional')),
                ('carga_horaria_total', models.PositiveIntegerField(verbose_name='Carga Horária Total')),
                ('carga_horaria_minima_certificado', models.PositiveIntegerField(verbose_name='Carga Horária Mínima para Certificado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='eventos.evento', verbose_name='Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_tematica', models.ManyToManyField(related_name='avaliadores', to='eventos.areatematica', verbose_name='Áreas Temáticas de Interesse')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliadores', to='eventos.evento', verbose_name='Evento')),
            ],
        ),
        migrations.AddField(
            model_name='areatematica',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_tematicas', to='eventos.evento', verbose_name='Evento'),
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presidente', models.BooleanField(default=False, verbose_name='Presidente')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='eventos.comissao', verbose_name='Comissão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=core.fields.FormatStringFileUpload('noticias/posters/{instance.id}/{filename}"'), verbose_name='Pôster')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.fields.FormatStringFileUpload('noticias/thumbnails/{instance.id}/{filename}'), verbose_name='Thumbnail')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='EventoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_documentos', to='documentos.documento', verbose_name='Documento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_documentos', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Evento-Documento',
                'verbose_name_plural': 'Eventos-Documentos',
                'unique_together': {('evento', 'documento')},
            },
        ),
    ]
