# Generated by Django 5.0.4 on 2024-08-29 06:05

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ano',
            field=models.CharField(default=core.fields.get_current_year_str, max_length=4, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
