# Generated by Django 5.0.4 on 2024-08-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_ano_alter_evento_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='texto_apresentacao',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de Apresentação'),
        ),
    ]
