# Generated by Django 5.0.4 on 2024-08-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_texto_apresentacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='carga_horaria_minima_certificado',
            new_name='ch_min_certificado',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='carga_horaria_total',
            new_name='ch_total',
        ),
    ]
