# Generated by Django 5.0.4 on 2024-08-29 07:28

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_rename_carga_horaria_minima_certificado_evento_ch_min_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='logo_mini',
            field=models.ImageField(blank=True, null=True, upload_to=core.fields.FormatStringFileUpload('eventos/logo/{instance.id}/{filename}'), verbose_name='Mini Logo'),
        ),
    ]
