# Generated by Django 5.0.4 on 2024-08-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_logo_mini'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Cando do Youtube'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Perfil no Instagram'),
        ),
    ]
