# Generated by Django 5.0.4 on 2024-08-31 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_evento_youtube_alter_evento_instagram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='texto_apresentacao',
            new_name='apresentacao',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='data_encerramento',
            new_name='dt_encerramento',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='data_inicio',
            new_name='dt_inicio',
        ),
    ]
