# Generated by Django 5.0.4 on 2024-08-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_rename_texto_apresentacao_evento_apresentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Canal do Youtube'),
        ),
    ]
