# Generated by Django 5.0.4 on 2024-08-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_alter_evento_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatematica',
            name='descricao',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='areatematica',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
