# Generated by Django 5.0.4 on 2024-08-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_areatematica_descricao_alter_areatematica_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatematica',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
