# Generated by Django 5.0.4 on 2024-08-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_alter_areatematica_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatematica',
            name='cor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='areatematica',
            name='icone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ícone'),
        ),
    ]
