# Generated by Django 5.0.4 on 2024-08-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_areatematica_cor_areatematica_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatematica',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='areatematica',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
