# Generated by Django 5.0.4 on 2024-09-02 10:29

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_alter_areatematica_descricao_alter_areatematica_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventodocumento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='ch_min_certificado',
            field=models.PositiveIntegerField(verbose_name='Mín. Certificado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ch_total',
            field=models.PositiveIntegerField(verbose_name='CH Total'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dt_encerramento',
            field=models.DateField(verbose_name='Encerramento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dt_inicio',
            field=models.DateField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.fields.FormatStringFileUpload('eventos/parceiros/{instance.id}/{filename}'), verbose_name='Logo')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parceiros', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
            },
        ),
    ]
