# Generated by Django 5.0.4 on 2024-09-02 10:52

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_alter_eventodocumento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliador',
            options={'verbose_name': 'Avaliador', 'verbose_name_plural': 'Avaliadores'},
        ),
        migrations.AlterModelOptions(
            name='comissao',
            options={'verbose_name': 'Comissão', 'verbose_name_plural': 'Comissões'},
        ),
        migrations.AlterModelOptions(
            name='membro',
            options={'verbose_name': 'Membro de Comissão', 'verbose_name_plural': 'Membros de Comissões'},
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='logo',
            field=models.ImageField(default='img/placeholders/default_logo.jpg', upload_to=core.fields.FormatStringFileUpload('eventos/parceiros/{instance.id}/{filename}'), verbose_name='Logo'),
        ),
    ]
