# Generated by Django 5.0.4 on 2024-09-02 11:05

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_alter_avaliador_options_alter_comissao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='poster',
            field=models.ImageField(default='img/placeholders/default_poster.jpg', upload_to=core.fields.FormatStringFileUpload('noticias/posters/{instance.id}/{filename}"'), verbose_name='Pôster'),
        ),
    ]
