# Generated by Django 5.0.4 on 2024-09-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_noticia_url_alter_noticia_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliador',
            old_name='areas_tematica',
            new_name='areas_tematicas',
        ),
    ]
