# Generated by Django 5.0.4 on 2024-09-06 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('eventos', '0016_rename_areas_tematica_avaliador_areas_tematicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='enderecos.endereco', verbose_name='Endereço'),
        ),
        migrations.CreateModel(
            name='EventoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contato_eventos', to='enderecos.contato')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_contatos', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Contato do Evento',
                'verbose_name_plural': 'Contatos do Evento',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='contatos',
            field=models.ManyToManyField(related_name='eventos', through='eventos.EventoContato', to='enderecos.contato', verbose_name='Contatos'),
        ),
    ]
