# Generated by Django 5.0.4 on 2024-09-07 14:12

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_evento_endereco_eventocontato_evento_contatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='video_promocional',
            field=models.FileField(blank=True, null=True, upload_to=core.fields.FormatStringFileUpload('eventos/video/{instance.id}/{filename}'), verbose_name='Video Promocional'),
        ),
    ]
