# Generated by Django 5.0.4 on 2024-09-09 17:07

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_alter_evento_video_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='poster',
            field=models.ImageField(default='img/placeholders/default_poster.jpg', upload_to=core.fields.FormatStringFileUpload('noticias/posters/{instance.id}/{filename}'), verbose_name='Pôster'),
        ),
    ]
