# Generated by Django 5.0.4 on 2024-09-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_inscricaoevento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricaoevento',
            options={'verbose_name': 'Inscrição em Evento', 'verbose_name_plural': 'Inscrições em Eventos'},
        ),
    ]
