# Generated by Django 5.0.4 on 2024-09-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_alter_inscricaoevento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ch_min_certificado',
            field=models.PositiveIntegerField(verbose_name='CH Mínima'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
