# Generated by Django 5.0.4 on 2024-09-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_alter_evento_ch_min_certificado_alter_noticia_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatematica',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
