# Generated by Django 5.0.4 on 2024-09-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0023_alter_areatematica_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='dt_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
    ]
