# Generated by Django 5.0.4 on 2024-10-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0024_noticia_dt_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ch_min_certificado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CH Mínima para Certificado'),
        ),
    ]
