# Generated by Django 5.0.4 on 2024-10-13 23:34

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_alter_evento_ch_min_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nome')),
                ('img', models.ImageField(default='img/placeholders/default_logo.jpg', upload_to=core.fields.FormatStringFileUpload('eventos/item/galeria/{instance.id}/{filename}'), verbose_name='Logo')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemGaleria', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'ItemGaleria',
                'verbose_name_plural': 'ItensGaleria',
            },
        ),
    ]
