# Generated by Django 5.0.4 on 2024-10-14 16:57

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0026_itemgaleria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgaleria',
            name='img',
            field=models.ImageField(default='img/placeholders/default_logo.jpg', upload_to=core.fields.FormatStringFileUpload('eventos/item/galeria/{filename}'), verbose_name='Logo'),
        ),
    ]
