# Generated by Django 5.0.4 on 2024-10-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_alter_itemgaleria_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgaleria',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
