# Generated by Django 5.0.4 on 2024-10-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0028_alter_itemgaleria_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgaleria',
            name='url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
    ]
