# Generated by Django 5.0.4 on 2024-11-06 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0029_alter_itemgaleria_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ira', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IRA')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitores', to='eventos.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
    ]
