# Generated by Django 5.0.4 on 2024-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0030_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='ano',
            field=models.PositiveIntegerField(default=1, verbose_name='Ano do Curso'),
        ),
    ]
