# Generated by Django 5.0.4 on 2024-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0031_monitor_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='selecionado',
            field=models.BooleanField(default=False, verbose_name='Status de seleção'),
        ),
    ]
