# Generated by Django 5.0.4 on 2024-11-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_monitor_selecionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='selecionado',
            field=models.BooleanField(default=False, verbose_name='Foi Selecionado?'),
        ),
    ]
