# Generated by Django 5.2.17 on 2026-09-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0033_alter_monitor_selecionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='certificado_signatario_assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/certificados/assinaturas/', verbose_name='Imagem da Assinatura dos Certificados'),
        ),
        migrations.AddField(
            model_name='evento',
            name='certificado_signatario_cargo',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cargo do Signatário dos Certificados'),
        ),
        migrations.AddField(
            model_name='evento',
            name='certificado_signatario_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome do Signatário dos Certificados'),
        ),
    ]
