# Generated by Django 5.0.4 on 2024-08-29 05:49

from django.db import migrations, models

from core.fields import FormatStringFileUpload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('file', models.FileField(upload_to=FormatStringFileUpload('documentos/{instance.id}/{fiename}'), verbose_name='Arquivo')),
                ('tipo', models.CharField(choices=[('estilo', 'Estilo'), ('download', 'Download'), ('trabalho', 'Trabalho'), ('regras', 'Regras'), ('modelo', 'Modelo')], max_length=20, verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
