# Generated by Django 5.0.4 on 2024-08-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(upload_to='documentos/', verbose_name='Arquivo'),
        ),
    ]
