# Generated by Django 5.0.4 on 2024-09-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('estilo', 'Estilo'), ('download', 'Download'), ('trabalho', 'Trabalho'), ('regra', 'Orientações'), ('modelo', 'Modelo')], max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
