# Generated by Django 5.0.4 on 2024-10-15 16:05

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(upload_to=core.fields.FormatStringFileUpload('documentos/{instance.id}/{filename}'), verbose_name='Arquivo'),
        ),
    ]
