# Generated by Django 5.0.2 on 2024-04-15 17:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('Linguagens, Códigos e suas Tecnologias', 'Linguagens, Códigos e suas Tecnologias'), ('Engenharias e suas Tecnologias', 'Engenharias e suas Tecnologias'), ('Ciências Exatas e da Terra e suas Tecnologias', 'Ciências Exatas e suas Tecnologias'), ('Ciências Humanas, Sociais e Aplicadas e suas Tecnologias', 'Ciências Humanas e suas Tecnologias'), ('Ciências da Natureza e suas Tecnologias', 'Ciências da Natureza e suas Tecnologias'), ('Ciências Agrárias e suas Tecnologias', 'Ciências Agrárias e suas Tecnologias'), ('Ciências da Saúde e suas Tecnologias', 'Ciências da Saúde e suas Tecnologias')], default='Ciências Agrárias e suas Tecnologias', max_length=300)),
                ('data_submissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Submissão: ')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('estado', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=40)),
                ('vinculo', models.CharField(max_length=40)),
                ('foto_perfil', models.FileField(blank=True, null=True, upload_to='fotos_perfil', verbose_name='Foto de Perfil do Usuário: ')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DadoComplementar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.CharField(max_length=100)),
                ('lider', models.BooleanField(default=False)),
                ('matricula', models.CharField(max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('submissao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.submissao')),
                ('artigo', models.FileField(upload_to='artigos_comunicacao')),
            ],
            bases=('usuarios.submissao',),
        ),
        migrations.AddField(
            model_name='submissao',
            name='coautor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
