# Generated by Django 5.0.4 on 2024-04-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poster',
            new_name='Artigo',
        ),
        migrations.RenameField(
            model_name='artigo',
            old_name='artigo',
            new_name='documento',
        ),
    ]
