# Generated by Django 5.0.4 on 2024-04-26 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_poster_artigo_rename_artigo_artigo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliadorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Linguagens, Códigos e suas Tecnologias', 'Linguagens, Códigos e suas Tecnologias'), ('Engenharias e suas Tecnologias', 'Engenharias e suas Tecnologias'), ('Ciências Exatas e da Terra e suas Tecnologias', 'Ciências Exatas e suas Tecnologias'), ('Ciências Humanas, Sociais e Aplicadas e suas Tecnologias', 'Ciências Humanas e suas Tecnologias'), ('Ciências da Natureza e suas Tecnologias', 'Ciências da Natureza e suas Tecnologias'), ('Ciências Agrárias e suas Tecnologias', 'Ciências Agrárias e suas Tecnologias'), ('Ciências da Saúde e suas Tecnologias', 'Ciências da Saúde e suas Tecnologias')], default='Ciências Agrárias e suas Tecnologias', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
