# Generated by Django 5.0.4 on 2024-05-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_areatematica'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatematica',
            name='descricao',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
