# Generated by Django 5.0.4 on 2024-05-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_areatematica_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='instituicao',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_completo',
            field=models.CharField(default='Nome Completo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cidade',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='1234', max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='vinculo',
            field=models.CharField(choices=[('Servidor IFRN', 'Servidor IFRN'), ('Aluno IFRN', 'Aluno IFRN'), ('Estudante Externo', 'Estudante Externo'), ('Profissional Externo', 'Profissional Externo'), ('Outro', 'Outro')], max_length=20),
        ),
    ]
