# Generated by Django 5.0.4 on 2024-08-29 05:49

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('usuarios', '0008_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_contatos', to='enderecos.contato', verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Contato do Usuário',
                'verbose_name_plural': 'Contatos do Usuário',
            },
        ),
        migrations.DeleteModel(
            name='AreaTematica',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='submissao_ptr',
        ),
        migrations.RemoveField(
            model_name='avaliadorprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comissao',
        ),
        migrations.RemoveField(
            model_name='dadocomplementar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='coautor',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estado',
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='enderecos.endereco', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to=core.fields.FormatStringFileUpload('usuarios/avatar/{instance.id}/{filename}'), verbose_name='Foto de Perfil do Usuário: '),
        ),
        migrations.AlterField(
            model_name='user',
            name='instituicao',
            field=models.CharField(blank=True, max_length=40, verbose_name='Instituição de Ensino '),
        ),
        migrations.AlterField(
            model_name='user',
            name='vinculo',
            field=models.CharField(choices=[('Servidor IFRN', 'Servidor IFRN'), ('Aluno IFRN', 'Aluno IFRN'), ('Estudante Externo', 'Estudante Externo'), ('Profissional Externo', 'Profissional Externo'), ('Outro', 'Outro')], max_length=30),
        ),
        migrations.AddField(
            model_name='usuariocontato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_contatos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='user',
            name='contatos',
            field=models.ManyToManyField(related_name='usuarios', through='usuarios.UsuarioContato', to='enderecos.contato', verbose_name='Contatos'),
        ),
        migrations.DeleteModel(
            name='Artigo',
        ),
        migrations.DeleteModel(
            name='AvaliadorProfile',
        ),
        migrations.DeleteModel(
            name='DadoComplementar',
        ),
        migrations.DeleteModel(
            name='Submissao',
        ),
        migrations.AlterUniqueTogether(
            name='usuariocontato',
            unique_together={('usuario', 'contato')},
        ),
    ]
