# Generated by Django 5.0.4 on 2024-09-07 03:33

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuariocontato_delete_areatematica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.FileField(blank=True, default='usuarios/avatar/placeholder.jpg', null=True, upload_to=core.fields.FormatStringFileUpload('usuarios/avatar/{instance.id}/{filename}'), verbose_name='Foto de Perfil do Usuário: '),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
