# Generated by Django 5.0.4 on 2024-09-11 19:23

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to=core.fields.FormatStringFileUpload('usuarios/avatar/{instance.id}/{filename}'), verbose_name='Foto de Perfil do Usuário: '),
        ),
    ]
