# Generated by Django 5.0.4 on 2024-10-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_user_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vinculo',
            field=models.CharField(choices=[('Servidor IFRN', 'Servidor IFRN'), ('Aluno IFRN', 'Aluno IFRN'), ('Estudante Externo', 'Estudante Externo'), ('Profissional Externo', 'Profissional Externo'), ('Outro', 'Outro')], default='Outro', max_length=30),
        ),
    ]
