# Generated by Django 5.0.4 on 2024-11-04 20:31

import core.fields
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_user_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=core.fields.FormatStringFileUpload('usuarios/avatar/{instance.id}/{filename}'), verbose_name='Foto de Perfil do Usuário: '),
        ),
    ]
