# Generated by Django 5.0.4 on 2024-08-29 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Descrição')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cor', models.CharField(max_length=7, verbose_name='Cor')),
                ('icone', models.CharField(max_length=100, verbose_name='Ícone')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_de_atividade', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Tipo de Atividade',
                'verbose_name_plural': 'Tipos de Atividade',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('vagas_limitadas', models.BooleanField(default=False, verbose_name='Tem Vagas Limitadas')),
                ('qtd_vagas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Vagas')),
                ('inicio_inscricoes', models.DateTimeField(verbose_name='Início das Inscrições')),
                ('fim_inscricoes', models.DateTimeField(verbose_name='Fim das Inscrições')),
                ('duracao', models.DurationField(verbose_name='Duração')),
                ('status', models.CharField(choices=[('inscricoes_abertas', 'Inscrições Abertas'), ('inscricoes_encerradas', 'Inscrições Encerradas'), ('sem_vaga', 'Sem Vaga'), ('inscricoes_embreve', 'Inscrições Em Breve'), ('rascunho', 'Rascunho')], max_length=30, verbose_name='Status')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='atividades.tipoatividade', verbose_name='Tipo de Atividade')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
    ]
