# Generated by Django 5.0.4 on 2024-08-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoatividade',
            name='cor',
            field=models.CharField(max_length=20, verbose_name='Cor'),
        ),
    ]
