# Generated by Django 5.0.4 on 2024-09-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_alter_tipoatividade_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoatividade',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='tipoatividade',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
