# Generated by Django 5.0.4 on 2024-09-13 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_alter_tipoatividade_icone_alter_tipoatividade_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False, verbose_name='Presente')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='atividades.atividade', verbose_name='Atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_atividades', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Inscrição em Atividade',
                'verbose_name_plural': 'Inscrições em Atividades',
                'unique_together': {('atividade', 'usuario')},
            },
        ),
    ]
