# Generated by Django 5.0.4 on 2024-09-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_inscricaoatividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='conteudo',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo Programático'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='materiais',
            field=models.TextField(blank=True, null=True, verbose_name='Materiais Necessários'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='metodologia',
            field=models.TextField(blank=True, null=True, verbose_name='Metodologia'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='objetivos',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='pre_requisitos',
            field=models.TextField(blank=True, null=True, verbose_name='Pré-requisitos do Público Alvo'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='publico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Público Alvo'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='referencias',
            field=models.TextField(blank=True, null=True, verbose_name='Referências Bibliográficas'),
        ),
    ]
