# Generated by Django 5.0.4 on 2024-09-19 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_atividade_conteudo_atividade_materiais_and_more'),
        ('eventos', '0022_alter_evento_ch_min_certificado_alter_noticia_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='inicio_inscricoes',
            field=models.DateTimeField(verbose_name='Iní. das Inscrições'),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Sala')),
                ('capacidade', models.PositiveIntegerField(verbose_name='Capacidade')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início')),
                ('fim', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fim')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='atividades.atividade', verbose_name='Atividade')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='atividades.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'unique_together': {('sala', 'atividade', 'inicio', 'fim')},
            },
        ),
    ]
