# Generated by Django 5.0.4 on 2024-09-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0006_alter_atividade_inicio_inscricoes_sala_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='capacidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade'),
        ),
    ]
