# Generated by Django 5.0.4 on 2024-09-19 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0007_alter_sala_capacidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='dia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='fim',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hr Fim'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='inicio',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hr Início'),
        ),
    ]
