# Generated by Django 5.0.4 on 2024-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0008_agendamento_dia_alter_agendamento_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='com_inscricoes',
            field=models.BooleanField(default=False, verbose_name='Permitir inscrições?'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='fim_inscricoes',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim das Inscrições'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='inicio_inscricoes',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Iní. das Inscrições'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(blank=True, choices=[('inscricoes_abertas', 'Inscrições Abertas'), ('inscricoes_encerradas', 'Inscrições Encerradas'), ('sem_vaga', 'Sem Vaga'), ('inscricoes_embreve', 'Inscrições Em Breve'), ('rascunho', 'Rascunho')], max_length=30, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='vagas_limitadas',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tem Vagas Limitadas'),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('sala', 'atividade', 'dia', 'inicio', 'fim')},
        ),
    ]
