# Generated by Django 5.0.4 on 2024-09-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0009_atividade_com_inscricoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='fim_inscricoes',
            field=models.DateField(blank=True, null=True, verbose_name='Fim das Inscrições'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='inicio_inscricoes',
            field=models.DateField(blank=True, null=True, verbose_name='Iní. das Inscrições'),
        ),
    ]
