# Generated by Django 5.0.4 on 2024-09-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0010_alter_atividade_fim_inscricoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='vagas_limitadas',
        ),
    ]
