# Generated by Django 5.0.4 on 2024-09-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0011_remove_atividade_vagas_limitadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoatividade',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
    ]
