# Generated by Django 5.0.4 on 2024-10-08 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0012_alter_tipoatividade_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('voluntário', 'Voluntário'), ('autor_principal', 'Autor Principal'), ('coautor', 'Coautor')], max_length=30, verbose_name='Papel')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='atividades.atividade', verbose_name='Atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_atividades', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Responsável pela Atividade',
                'verbose_name_plural': 'Responsáveis pelas Atividades',
                'unique_together': {('atividade', 'usuario')},
            },
        ),
    ]
