# Generated by Django 5.0.4 on 2024-10-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0013_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='papel',
            field=models.CharField(choices=[('autor_principal', 'Autor Principal'), ('coautor', 'Coautor'), ('voluntário', 'Voluntário')], max_length=30, verbose_name='Papel'),
        ),
    ]
