# Generated by Django 5.0.4 on 2024-10-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0014_alter_responsavel_papel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(blank=True, choices=[('inscricoes_abertas', 'Inscrições Abertas'), ('inscricoes_encerradas', 'Inscrições Encerradas'), ('sem_vaga', 'Sem Vaga'), ('inscricoes_embreve', 'Inscrições Em Breve'), ('rascunho', 'Rascunho')], default='rascunho', max_length=30, null=True, verbose_name='Status'),
        ),
    ]
