# Generated by Django 5.0.4 on 2024-11-04 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0015_alter_atividade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='fim',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Hr Fim'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='inicio',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Hr Início'),
        ),
    ]
