# Generated by Django 5.0.4 on 2024-09-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='local',
            field=models.CharField(max_length=50, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(default='São Paulo do Potengi', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(default='Rio Grande do Norte', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50, verbose_name='País'),
        ),
    ]
