# Generated by Django 5.0.4 on 2024-09-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_endereco_local_alter_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='local',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local'),
        ),
    ]
