# Generated by Django 5.0.4 on 2024-09-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0002_alter_documento_file'),
        ('eventos', '0019_alter_noticia_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('min_avaliacoes', models.PositiveIntegerField(verbose_name='Mínimo de Avaliações')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Chamada',
                'verbose_name_plural': 'Chamadas',
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField(verbose_name='Data de Início')),
                ('dt_encerramento', models.DateField(verbose_name='Data de Encerramento')),
                ('tipo', models.CharField(choices=[('parcial', 'Parcial'), ('apresentacao', 'Apresentação'), ('final', 'Final')], max_length=20, verbose_name='Tipo de Deadline')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('encerrado', 'Encerrado'), ('em_breve', 'Em Breve'), ('rascunho', 'Rascunho')], default='em_breve', max_length=20, verbose_name='Status')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='chamadas.chamada', verbose_name='Chamada')),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlines',
            },
        ),
        migrations.CreateModel(
            name='CriterioAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('peso', models.PositiveIntegerField(verbose_name='Peso')),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_avaliacao', to='chamadas.deadline', verbose_name='Deadline')),
            ],
            options={
                'verbose_name': 'Critério de Avaliação',
                'verbose_name_plural': 'Critérios de Avaliação',
            },
        ),
        migrations.CreateModel(
            name='ChamadaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamada_documentos', to='chamadas.chamada', verbose_name='Documento')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamada_documentos', to='documentos.documento', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'unique_together': {('chamada', 'documento')},
            },
        ),
    ]
