# Generated by Django 5.0.4 on 2024-09-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamada',
            name='titulo',
        ),
        migrations.AddField(
            model_name='chamada',
            name='nome',
            field=models.CharField(default=' ', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
