# Generated by Django 5.0.4 on 2024-09-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0002_remove_chamada_titulo_chamada_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterioavaliacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='criterioavaliacao',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
