# Generated by Django 5.0.4 on 2024-09-17 07:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0003_alter_criterioavaliacao_descricao_and_more'),
        ('documentos', '0003_alter_documento_tipo'),
        ('eventos', '0022_alter_evento_ch_min_certificado_alter_noticia_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='chamada',
        ),
        migrations.RemoveField(
            model_name='criterioavaliacao',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='chamada',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='chamada',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='chamada',
            name='min_avaliacoes',
        ),
        migrations.RemoveField(
            model_name='chamada',
            name='nome',
        ),
        migrations.AddField(
            model_name='chamada',
            name='dt_encerramento',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Encerramento'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='dt_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='etapa',
            field=models.CharField(choices=[('inicial', 'Inicial'), ('apresentacao', 'Apresentação'), ('final', 'Final')], default='inicial', max_length=20, verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('encerrado', 'Encerrado'), ('em_breve', 'Em Breve'), ('rascunho', 'Rascunho')], default='em_breve', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='criterioavaliacao',
            name='chamada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criterios_avaliacao', to='chamadas.chamada', verbose_name='Chamada'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TipoChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('min_avaliacoes', models.PositiveIntegerField(verbose_name='Mínimo de Avaliações')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_chamadas', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Tipo de Chamada',
                'verbose_name_plural': 'Tipos de Chamadas',
            },
        ),
        migrations.AddField(
            model_name='chamada',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='chamadas.tipochamada', verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TipoChamadaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_chamada_documentos', to='documentos.documento', verbose_name='Documento')),
                ('tipo_chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_chamada_documentos', to='chamadas.tipochamada', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.DeleteModel(
            name='ChamadaDocumento',
        ),
    ]
