# Generated by Django 5.0.4 on 2024-09-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0004_remove_deadline_chamada_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deadline',
        ),
        migrations.AlterUniqueTogether(
            name='tipochamadadocumento',
            unique_together={('tipo_chamada', 'documento')},
        ),
    ]
