# Generated by Django 5.0.4 on 2024-10-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0005_delete_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='forma_calculo',
            field=models.CharField(choices=[('soma', 'Soma'), ('media_aritmetica', 'Média Aritmética'), ('media_ponderada', 'Média Ponderada')], default='media_ponderada', max_length=20, verbose_name='Forma de Cálculo'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='tem_submissao',
            field=models.BooleanField(default=True, verbose_name='Tem Submissão'),
        ),
    ]
