# Generated by Django 5.0.4 on 2024-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0006_chamada_forma_calculo_chamada_tem_submissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamada',
            name='forma_calculo',
        ),
        migrations.AddField(
            model_name='chamada',
            name='forma_avaliacao',
            field=models.CharField(choices=[('sem', 'Sem Avaliação'), ('soma', 'Soma Simples'), ('media_aritmetica', 'Média Aritmética'), ('media_ponderada', 'Média Ponderada')], default='media_ponderada', max_length=20, verbose_name='Forma de Avaliação'),
        ),
    ]
