# Generated by Django 5.0.4 on 2024-10-15 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0007_remove_chamada_forma_calculo_chamada_forma_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='min_aprovacoes',
            field=models.PositiveIntegerField(default=1, verbose_name='Mínimo de Aprovações'),
        ),
        migrations.AddField(
            model_name='tipochamada',
            name='max_autores',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Máximo de Autores'),
        ),
        migrations.AlterField(
            model_name='tipochamada',
            name='min_avaliacoes',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Mínimo de Avaliações'),
        ),
    ]
