# Generated by Django 5.0.4 on 2024-10-18 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0008_chamada_min_aprovacoes_tipochamada_max_autores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipochamada',
            name='min_avaliacoes',
        ),
        migrations.AddField(
            model_name='chamada',
            name='min_avaliacoes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Mínimo de Avaliações'),
        ),
    ]
