# Generated by Django 5.0.4 on 2024-10-24 12:05

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0009_remove_tipochamada_min_avaliacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipochamada',
            name='opcoes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('RESUMO', 'Resumo'), ('DESCRICAO', 'Descrição')], default='RESUMO', max_length=255, null=True, verbose_name='Campos opcionais'),
        ),
    ]
