# Generated by Django 5.0.4 on 2024-10-24 14:10

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0010_tipochamada_opcoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipochamada',
            name='opcoes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('RESUMO', 'Resumo'), ('DESCRICAO', 'Descrição')], default='RESUMO', max_length=255, null=True, verbose_name='Campos opcionais'),
        ),
    ]
