# Generated by Django 5.0.4 on 2024-09-15 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0021_alter_inscricaoevento_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submetido', models.IntegerField(default=0)),
                ('em_avaliacao', models.IntegerField(default=0)),
                ('aprovado', models.IntegerField(default=0)),
                ('aprovado_com_ressalvas', models.IntegerField(default=0)),
                ('reprovado', models.IntegerField(default=0)),
                ('apresentado', models.IntegerField(default=0)),
                ('nao_apresentado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('resumo', models.CharField(max_length=1000)),
                ('palavras_chave', models.CharField(max_length=50)),
                ('area_tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.areatematica')),
                ('autor_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos_autor_principal', to=settings.AUTH_USER_MODEL)),
                ('coautores', models.ManyToManyField(related_name='trabalhos_coautores', to=settings.AUTH_USER_MODEL)),
                ('status', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabalho_status', to='submissao.statustrabalho')),
                ('tipo_chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.chamada')),
            ],
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identificado', models.FileField(upload_to='submissoes')),
                ('documento_nao_identificado', models.FileField(upload_to='submissoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissao.trabalho')),
            ],
        ),
        migrations.AddField(
            model_name='statustrabalho',
            name='trabalho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_do_trabalho', to='submissao.trabalho'),
        ),
    ]
