# Generated by Django 5.0.4 on 2024-10-15 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0008_chamada_min_aprovacoes_tipochamada_max_autores_and_more'),
        ('documentos', '0007_alter_documento_file'),
        ('eventos', '0027_alter_itemgaleria_img'),
        ('submissao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Submetido'), ('EM_AVALIACAO', 'Em Avaliação'), ('AVALIADO', 'Avaliado'), ('APROVADO', 'Aprovado'), ('APROVADO_C_RESSALVAS', 'Aprovado com Ressalvas'), ('REPROVADO', 'Reprovado')], default='RASCUNHO', max_length=50),
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='documento_identificado',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='documento_nao_identificado',
        ),
        migrations.AddField(
            model_name='submissao',
            name='chamada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='chamadas.chamada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='documentos.documento', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='submissao',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Parecer'),
        ),
        migrations.AddField(
            model_name='submissao',
            name='status_avaliacao',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Submetido'), ('EM_AVALIACAO', 'Em Avaliação'), ('AVALIADO', 'Avaliado'), ('APROVADO', 'Aprovado'), ('APROVADO_C_RESSALVAS', 'Aprovado com Ressalvas'), ('REPROVADO', 'Reprovado')], default='SOLICITADA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='submissao.trabalho'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='area_tematica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabalhos', to='eventos.areatematica', verbose_name='Área Temática'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='autor_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabalhos_autor_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='coautores',
            field=models.ManyToManyField(blank=True, related_name='trabalhos_coautores', to=settings.AUTH_USER_MODEL, verbose_name='Coautores'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='palavras_chave',
            field=models.CharField(max_length=100, verbose_name='Palavras-chave'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='resumo',
            field=models.CharField(max_length=3000, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='tipo_chamada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabalhos', to='chamadas.tipochamada'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLICITADA', 'Avaliação Solicitada'), ('CANCELADA', 'Cancelada Avaliação'), ('EM_AVALIACAO', 'Em Avaliação'), ('ACEITO', 'Trabalho Aceito'), ('RECUSADO', 'Trabalho Recusado'), ('ACEITO_C_RESSALVAS', 'Trabalho Aceito com Ressalvas'), ('NA', '-')], default='SOLICITADA', max_length=50)),
                ('nota_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='eventos.avaliador')),
                ('submissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='submissao.submissao')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_criterio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota')),
                ('comentario', models.TextField(blank=True, max_length=100, null=True, verbose_name='Comentário')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_criterios', to='submissao.avaliacao')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_criterios', to='chamadas.criterioavaliacao')),
            ],
            options={
                'verbose_name': 'Avaliação de Critério',
                'verbose_name_plural': 'Avaliações de Critérios',
            },
        ),
        migrations.DeleteModel(
            name='StatusTrabalho',
        ),
    ]
