# Generated by Django 5.0.4 on 2024-10-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0002_alter_trabalho_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('SOLICITADA', 'Aguardando Avaliação'), ('CANCELADA', 'Cancelada Avaliação'), ('EM_AVALIACAO', 'Em Avaliação'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('ACEITO_C_RESSALVAS', 'Aceito com Ressalvas'), ('NA', '-'), ('APRESENTADO', 'Apresentado'), ('NAO_APRESENTADO', 'Não Apresentado')], default='SOLICITADA', max_length=50),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='status_avaliacao',
            field=models.CharField(choices=[('SOLICITADA', 'Aguardando Avaliação'), ('CANCELADA', 'Cancelada Avaliação'), ('EM_AVALIACAO', 'Em Avaliação'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('ACEITO_C_RESSALVAS', 'Aceito com Ressalvas'), ('NA', '-'), ('APRESENTADO', 'Apresentado'), ('NAO_APRESENTADO', 'Não Apresentado')], default='SOLICITADA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Submetido'), ('EM_AVALIACAO', 'Em Avaliação'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='RASCUNHO', max_length=50),
        ),
    ]
