# Generated by Django 5.0.4 on 2024-10-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0003_alter_avaliacao_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
