# Generated by Django 5.0.4 on 2024-10-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0004_alter_avaliacao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Avaliação'),
        ),
    ]
