
# Generated by Django 5.0.4 on 2024-10-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0005_alter_submissao_nota_final'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissao',
            options={'verbose_name': 'Submissão', 'verbose_name_plural': 'Submissões'},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('SOLICITADA', 'Aguardando Avaliação'), ('CANCELADA', 'Cancelada Avaliação'), ('EM_AVALIACAO', 'Em Avaliação'), ('CONCLUIDA', 'Concluida'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('ACEITO_C_RESSALVAS', 'Aceito com Ressalvas'), ('APRESENTADO', 'Apresentado'), ('NAO_APRESENTADO', 'Não Apresentado')], default='SOLICITADA', max_length=50),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='status_avaliacao',
            field=models.CharField(choices=[('SOLICITADA', 'Aguardando Avaliação'), ('CANCELADA', 'Cancelada Avaliação'), ('EM_AVALIACAO', 'Em Avaliação'), ('CONCLUIDA', 'Concluida'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('ACEITO_C_RESSALVAS', 'Aceito com Ressalvas'), ('APRESENTADO', 'Apresentado'), ('NAO_APRESENTADO', 'Não Apresentado')], default='SOLICITADA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Submetido'), ('EM_AVALIACAO', 'Em Avaliação'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('APRESENTADO', 'Apresentado'), ('N_APRESENTADO', 'Não Apresentado')], default='RASCUNHO', max_length=50),
        ),
    ]
