# Generated by Django 5.0.4 on 2024-10-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0006_alter_submissao_options_alter_avaliacao_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='descricao',
            field=models.CharField(max_length=3000, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='palavras_chave',
            field=models.CharField(max_length=100, null=True, verbose_name='Palavras-chave'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='resumo',
            field=models.CharField(max_length=3000, null=True, verbose_name='Resumo'),
        ),
    ]
