# Generated by Django 5.0.4 on 2024-10-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0007_trabalho_descricao_alter_trabalho_palavras_chave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
