# Generated by Django 5.0.4 on 2024-10-25 06:11

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0008_trabalho_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Comentário Geral'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='dt_limite_aceite',
            field=models.DateField(blank=True, default=datetime.date(2024, 10, 25), null=True, validators=[core.models.validate_future_date], verbose_name='Data Limite de Aceite'),
        ),
    ]
