# Generated by Django 5.0.4 on 2024-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0010_alter_avaliacao_dt_limite_aceite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Comentário Geral'),
        ),
    ]
