# Generated by Django 5.0.4 on 2024-10-26 18:03

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0011_alter_avaliacao_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='dt_limite_aceite',
            field=models.DateField(default=datetime.date(2024, 10, 26), validators=[core.models.validate_future_date], verbose_name='Data Limite de Aceite'),
        ),
    ]
