# Generated by Django 5.0.4 on 2024-10-29 04:21

import core.models

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0012_alter_avaliacao_dt_limite_aceite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='dt_limite_aceite',
            field=models.DateField(default=core.models.get_hoje, validators=[core.models.validate_future_date], verbose_name='Data Limite de Aceite'),
        ),
    ]
